### PR TITLE
[ENH] Link Selection

### PR DESCRIPTION
**Pull request by ales-erjavec**
Closes https://github.com/biolab/orange-canvas-core/issues/46

Implement link selection and deletion.

### CODE REVIEW

**Comment by irgolic** [comment]
Hey, this is amazing. I especially like how signal names are smaller now. 

If you use Orange with signal names shown it looks great, but with signal names turned off, it looks weird when a link is selected. We could try force-showing the signal name on selection (and on hover?).

One bug I've found, it appears that with this PR, links don't fade out properly – the background shadow instantly disappears.

I'll try playing around with stuff like making the link's shadow blue on selection, as well as some of the other stuff outlined in #116.

**Comment by ajdapretnar** [comment]
In favour of force-showing the signal name on selection. On hover? I already think Orange does too many things on hover. I suppose it is distracting for a power user, but not sure about beginners. Could be useful for them.

**Comment by irgolic** [comment]
> In favour of force-showing the signal name on selection. On hover? I already think Orange does too many things on hover. I suppose it is distracting for a power user, but not sure about beginners. Could be useful for them.

After discussing this with @ajdapretnar, we've opted for a setting with three options. Show channel names between widgets:
- Always
- On hover
- Never

**Comment by ales-erjavec** [comment]
>  links don't fade out properly – the background shadow instantly disappears.

I think this should now be fixed.

**Pull request merged**
