### PR TITLE
addons: Remove orange3- from names

### PR DESCRIPTION
**Pull request by irgolic**
I didn't know I needed this but now I can't live without it.

Screenshot 2020-11-10 at 20 09 29

### CODE REVIEW

**Comment by markotoplak** [comment]
Hm, I remember that a while ago it looked like this. When did they come back? :)

**Comment by irgolic** [comment]
No idea, I always remember it with the `Orange3`'s, it's in the package name after all.

The way I've implemented this is by parsing the package name, might not be the best way, but I can't think of a better one, given this is queried directly @ PyPi.

Let me also add title case space splitting.

**Comment by markotoplak** [comment]
So, before Orange 3.23 we used to have:

```
def cleanup(name, sep="-"):
    """Used for sanitizing addon names. The function removes Orange/Orange3
    from the name and adds spaces before upper letters of the leftover to
    separate its words."""
    prefix, separator, postfix = name.partition(sep)
    name = postfix if separator == sep else prefix
    return " ".join(re.findall("[A-Z][a-z]*", name[0].upper() + name[1:]))
```

Which gave

Screenshot 2020-11-13 at 13 33 18

This one looks fine too. :)

**Comment by markotoplak** [comment]
Only after merging I remembered... @ales-erjavec, did you perhaps intentionally leave this feature out when separating canvas-core? Now other projects might use canvas-core and maybe they would not want to have names arbitrary rewritten...

**Pull request merged**
