### PR TITLE
[FIX] dropshadow: Device pixel ratio change

### PR DESCRIPTION
**Pull request by ales-erjavec**
Fixes gh-5

Invalidate the cached pixmap for devicePixelRatio change.

### CODE REVIEW

**Comment by ajdapretnar** [comment]
@NejcDebevec Could you please check?

**Comment by PrimozGodec** [comment]
It also happened to me when moving Orange from external screen to laptop screen. In my case, this PR fixes the issue.

**Comment by NejcDebevec** [comment]
@ales-erjavec  @ajdapretnar Now I get a new error. 

```
-[NSApplication runModalSession:] may not be invoked inside of transaction begin/commit pair, or inside of transaction commit (usually this means it was invoked inside of a view's -drawRect: method.) The modal dialog has been suppressed to avoid deadlock. (
	0   AppKit                              0x00007fff3a72ca59 -[NSApplication runModalSession:] + 187
	1   libqcocoa.dylib                     0x0000000127425a7b qt_plugin_instance + 177275
	2   QtCore                              0x000000010ad9dcff _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE + 431
	3   QtWidgets                           0x000000010bbd38ae _ZN7QDialog4execEv + 526
	4   QtWidgets.so                        0x000000010b68c4e4 _ZL17meth_QDialog_execP7_objectS0_ + 164
	5   python                              0x0000000108a4318e _PyMethodDef_RawFastCallKeywords + 350
	6   python                              0x0000000108b7fe42 call_function + 306
	7   python                              0x0000000108b7daec _PyEval_EvalFrameDefault + 46092
	8   python                              0x0000000108b7149e _PyEval_EvalCodeWithName + 414
	9   python                              0x0000000108a41de7 _PyFunction_FastCallDict + 231
	10  python                              0x0000000108b7dd58 _PyEval_EvalFrameDefault + 46712
	11  python                              0x0000000108b7149e _PyEval_EvalCodeWithName + 414
	12  python                              0x0000000108a42fe3 _PyFunction_FastCallKeywords + 195
	13  python                              0x0000000108b7fdc7 call_function + 183
	14  python                              0x0000000108b7daec _PyEval_EvalFrameDefault + 46092
	15  python                              0x0000000108a428d5 function_code_fastcall + 117
	16  QtCore.so                           0x000000010b2cd007 _ZNK8PyQtSlot4callEP7_objectS1_ + 39
	17  QtCore.so                           0x000000010b2ccf16 _ZNK8PyQtSlot6invokeEPPvP7_objectS0_b + 374
	18  QtCore.so                           0x000000010b2cda15 _ZN13PyQtSlotProxy7unislotEPPv + 85
	19  QtCore.so                           0x000000010b2cd98a _ZN13PyQtSlotProxy11qt_metacallEN11QMetaObject4CallEiPPv + 58
	20  QtCore                              0x000000010add34ed _ZN11QMetaObject8activateEP7QObjectiiPPv + 1773
	21  QtCore.so                           0x000000010b2c971f _ZL20pyqtBoundSignal_emitP7_objectS0_ + 655
	22  python                              0x0000000108a4318e _PyMethodDef_RawFastCallKeywords + 350
	23  python                              0x0000000108a4fe64 _PyMethodDescr_FastCallKeywords + 84
	24  python                              0x0000000108b7fec5 call_function + 437
	25  python                              0x0000000108b7da56 _PyEval_EvalFrameDefault + 45942
	26  python                              0x0000000108a428d5 function_code_fastcall + 117
	27  python                              0x0000000108ac246d slot_tp_call + 189
	28  python                              0x0000000108a41af5 _PyObject_FastCallDict + 245
	29  python                              0x0000000108bd4beb PyErr_PrintEx + 411
	30  QtCore.so                           0x000000010b2c7c2a _Z15pyqt5_err_printv + 122
	31  sip.so                              0x000000010a8f5dc8 sip_api_call_procedure_method + 245
	32  QtWidgets.so                        0x000000010b5badb7 _ZN10sipQWidget10paintEventEP11QPaintEvent + 103
	33  QtWidgets                           0x000000010ba12c28 _ZN7QWidget5eventEP6QEvent + 1096
	34  QtWidgets.so                        0x000000010b5bbc80 _ZN10sipQWidget5eventEP6QEvent + 192
	35  QtWidgets                           0x000000010b9d6c3d _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent + 269
	36  QtWidgets                           0x000000010b9d8042 _ZN12QApplication6notifyEP7QObjectP6QEvent + 594
	37  QtWidgets.so                        0x000000010b5a53ca _ZN15sipQApplication6notifyEP7QObjectP6QEvent + 234
	38  QtCore                              0x000000010ada26e4 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent + 212
	39  QtWidgets                           0x000000010ba0b8af _ZN14QWidgetPrivate10drawWidgetEP12QPaintDeviceRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore + 3135
	40  QtWidgets                           0x000000010ba0c020 _ZN14QWidgetPrivate22paintSiblingsRecursiveEP12QPaintDeviceRK5QListIP7QObjectEiRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore + 1120
	41  QtWidgets                           0x000000010ba0bebd _ZN14QWidgetPrivate22paintSiblingsRecursiveEP12QPaintDeviceRK5QListIP7QObjectEiRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore + 765
	42  QtWidgets                           0x000000010ba0bebd _ZN14QWidgetPrivate22paintSiblingsRecursiveEP12QPaintDeviceRK5QListIP7QObjectEiRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore + 765
	43  QtWidgets                           0x000000010ba0ba17 _ZN14QWidgetPrivate10drawWidgetEP12QPaintDeviceRK7QRegionRK6QPointiP8QPainterP19QWidgetBackingStore + 3495
	44  QtWidgets                           0x000000010b9e45e4 _ZN14QWidgetPrivate10scrollRectERK5QRectii + 9380
	45  QtWidgets                           0x000000010ba12e4d _ZN7QWidget5eventEP6QEvent + 1645
	46  QtWidgets                           0x000000010bb23eb5 _ZN11QMainWindow5eventEP6QEvent + 277
	47  QtWidgets.so                        0x000000010b61831b _ZL22meth_QMainWindow_eventP7_objectS0_ + 139
	48  python                              0x0000000108a4318e _PyMethodDef_RawFastCallKeywords + 350
	49  python                              0x0000000108b7fe42 call_function + 306
	50  python                              0x0000000108b7daec _PyEval_EvalFrameDefault + 46092
	51  python                              0x0000000108b7149e _PyEval_EvalCodeWithName + 414
	52  python                              0x0000000108a41de7 _PyFunction_FastCallDict + 231
	53  python                              0x0000000108a45ce2 method_call + 130
	54  python                              0x0000000108a43752 PyObject_Call + 130
	55  sip.so                              0x000000010a8f9f6e call_method + 76
	56  sip.so                              0x000000010a8f5ca4 sip_api_call_method + 136
	57  QtWidgets.so                        0x000000010b4f9e2b _ZN14sipQMainWindow5eventEP6QEvent + 123
	58  QtWidgets                           0x000000010b9d6c3d _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent + 269
	59  QtWidgets                           0x000000010b9d8042 _ZN12QApplication6notifyEP7QObjectP6QEvent + 594
	60  QtWidgets.so                        0x000000010b5a53ca _ZN15sipQApplication6notifyEP7QObjectP6QEvent + 234
	61  QtCore                              0x000000010ada26e4 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent + 212
	62  QtWidgets                           0x000000010b9dfa19 _ZN12QApplication11qt_metacallEN11QMetaObject4CallEiPPv + 7113
	63  QtWidgets                           0x000000010b9e027d _ZN12QApplication11qt_metacallEN11QMetaObject4CallEiPPv + 9261
	64  QtWidgets                           0x000000010ba348cc _ZN14QDesktopWidget11qt_metacallEN11QMetaObject4CallEiPPv + 20092
	65  QtCore                              0x000000010add3a3c _ZN11QMetaObject8activateEP7QObjectiiPPv + 3132
	66  QtGui                               0x000000010a3e14bb _ZN14QWindowPrivate26emitScreenChangedRecursionEP7QScreen + 75
	67  QtGui                               0x000000010a3e1873 _ZN14QWindowPrivate17setTopLevelScreenEP7QScreenb + 755
	68  QtGui                               0x000000010a3d9a08 _ZN22QGuiApplicationPrivate31processWindowScreenChangedEventEPN29QWindowSystemInterfacePrivate24WindowScreenChangedEventE + 152
	69  QtGui                               0x000000010a3b92f3 _ZN29QWindowSystemInterfacePrivate23handleWindowSystemEventIN22QWindowSystemInterface19SynchronousDeliveryEEEbPNS_17WindowSystemEventE + 115
	70  libqcocoa.dylib                     0x000000012740f40e qt_plugin_instance + 85518
	71  QtCore                              0x000000010adaca7f _ZNK11QMetaMethod6invokeEP7QObjectN2Qt14ConnectionTypeE22QGenericReturnArgument16QGenericArgumentS5_S5_S5_S5_S5_S5_S5_S5_S5_ + 1295
	72  libqcocoa.dylib                     0x00000001274127a0 qt_plugin_instance + 98720
	73  Foundation                          0x00007fff3eec4640 -[__NSObserver _doit:] + 303
	74  CoreFoundation                      0x00007fff3cd9c61c __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
	75  CoreFoundation                      0x00007fff3cd9c4ea _CFXRegistrationPost + 458
	76  CoreFoundation                      0x00007fff3cd9c221 ___CFXNotificationPost_block_invoke + 225
	77  CoreFoundation                      0x00007fff3cd5ad72 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1826
	78  CoreFoundation                      0x00007fff3cd59e03 _CFXNotificationPost + 659
	79  Foundation                          0x00007fff3ee838c7 -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
	80  AppKit                              0x00007fff3a439c0c NSPerformVisuallyAtomicChange + 146
	81  AppKit                              0x00007fff3a3bf04c -[NSWindow _updateSettingsSendingScreenChangeNotificationIfNeeded:] + 193
	82  AppKit                              0x00007fff3a3be89f -[NSWindow _setFrame:updateBorderViewSize:] + 1145
	83  AppKit                              0x00007fff3a3be41d -[NSWindow _setFrame:] + 58
	84  AppKit                              0x00007fff3a50a9cb -[NSWindow _windowMovedToRect:] + 178
	85  AppKit                              0x00007fff3a50a811 -[NSWindow _windowMoved:] + 1093
	86  AppKit                              0x00007fff3abe4bae -[NSWindow _internalHandleAppKitDefinedEvent:] + 239
	87  AppKit                              0x00007fff3ac49147 -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] + 4282
	88  AppKit                              0x00007fff3ac47c70 -[NSWindow(NSEventRouting) sendEvent:] + 497
	89  libqcocoa.dylib                     0x00000001274222d5 qt_plugin_instance + 163029
	90  AppKit                              0x00007fff3aaa9236 -[NSApplication(NSEvent) sendEvent:] + 2462
	91  libqcocoa.dylib                     0x000000012742929a qt_plugin_instance + 191642
	92  AppKit                              0x00007fff3a3098b5 -[NSApplication run] + 812
	93  libqcocoa.dylib                     0x0000000127425b7b qt_plugin_instance + 177531
	94  QtCore                              0x000000010ad9dcff _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE + 431
	95  QtCore                              0x000000010ada2cf2 _ZN16QCoreApplication4execEv + 130
	96  QtWidgets.so                        0x000000010b6947d2 _ZL23meth_QApplication_exec_P7_objectS0_ + 82
	97  python                              0x0000000108a4318e _PyMethodDef_RawFastCallKeywords + 350
	98  python                              0x0000000108b7fe42 call_function + 306
	99  python                              0x0000000108b7daec _PyEval_EvalFrameDefault + 46092
	100 python                              0x0000000108b7149e _PyEval_EvalCodeWithName + 414
	101 python                              0x0000000108a42fe3 _PyFunction_FastCallKeywords + 195
	102 python                              0x0000000108b7fdc7 call_function + 183
	103 python                              0x0000000108b7db27 _PyEval_EvalFrameDefault + 46151
	104 python                              0x0000000108b7149e _PyEval_EvalCodeWithName + 414
	105 python                              0x0000000108bd49a0 PyRun_FileExFlags + 256
	106 python                              0x0000000108bd3e17 PyRun_SimpleFileExFlags + 391
	107 python                              0x0000000108c01d3f pymain_main + 9663
	108 python                              0x0000000108a1566d main + 125
	109 libdyld.dylib                       0x00007fff64c2d015 start + 1
	110 ???                                 0x0000000000000004 0x0 + 4
)
```

**Comment by ales-erjavec** [comment]
@NejcDebevec can you please locate [`Orange/canvas/__main__.py` line L497](https://github.com/biolab/orange3/blob/master/Orange/canvas/__main__.py#L497) in your installation and delete line 497
```diff
diff --git a/Orange/canvas/__main__.py b/Orange/canvas/__main__.py
index d91e7e836..04857b9eb 100644
--- a/Orange/canvas/__main__.py
+++ b/Orange/canvas/__main__.py
@@ -494,7 +494,6 @@ def main(argv=None):
     try:
         with closing(stdout),\
              closing(stderr),\
-             patch('sys.excepthook', excepthook),\
              patch('sys.stderr', stderr),\
              patch('sys.stdout', stdout):
             status = app.exec_()
```
and rerun to hopefully get more informative error.

**Pull request merged**
