### PR TITLE
[ENH] Color styled widget icons

### PR DESCRIPTION
**Pull request by ales-erjavec**
### Issue

Fixes: gh-270

### Changes

Color widget icons based on current palette where appropriate.

By default when running in dark mode the colors are inverted to fit the background to foreground grayscale range.

Screenshot_20230511_143619

Screenshot_20230511_143839

Note that 'Color' is quite badly drawn.

But also add support for explicitly using *palette styled* widget icons like in https://github.com/biolab/orange3/pull/6444

Screenshot_20230511_152623

Screenshot_20230511_152231

### CODE REVIEW

**Comment by PrimozGodec** [comment]
After checkout, these branch icons are oversized (see screenshot below). My setup is a laptop with a retina screen and an external "normal" screen plugged in. Everything is fine when I open Orange on the retina or only use an external screen. The problem happens when both screens are on, and I open orange on the external screen.

Screenshot 2023-05-26 at 08 36 27

**Comment by ales-erjavec** [comment]
> After checkout, these branch icons are oversized (see screenshot below). My setup is a laptop with a retina screen and an external "normal" screen plugged in.

Is this happening using Qt6?

**Comment by PrimozGodec** [comment]
> Is this happening using Qt6?

Yes, I have PyQt6. I can also try it later on PyQt5.

**Comment by ales-erjavec** [comment]
Can you check again with the latest version.

**Comment by PrimozGodec** [comment]
> Can you check again with the latest version.

It looks good now.

**Pull request merged**
