### PR TITLE
Render descriptions in markdown

### PR DESCRIPTION
**Pull request by rokgomiscek**
##### Issue
Descriptions in markdown did not render correctly

##### Description of changes
Added markdown rendering for the appropriate content type.

##### Includes
- [X] Code changes
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by ales-erjavec** [comment]
I cannot duplicate the issue on master. Can you check again or describe the issue in more detail.

**Comment by rokgomiscek** [comment]
On Windows using Orange 3.26. 
The Add-ons window looks like this
image

**Comment by ales-erjavec** [comment]
Can you check that you have commonmark>=0.8.1 installed in the python environment.

**Comment by ales-erjavec** [comment]
Also maybe try force uninstalling and installing commonmark.  It is possible that on case insensitive file systems an update from commonmark 0.7* -> 0.8.* that goes via `setup.py install` route without a previous uninstall leaves the package broken.

**Comment by ajdapretnar** [comment]
Closed in favour of #121

**Pull request closed without merging**
