### PR TITLE
[ENH] Smooth horizontal scrolling

### PR DESCRIPTION
**Pull request by irgolic**
Currently, if you hold shift and scroll, each turn of the scroll wheel will scroll a full horizontal distance (at least with my mouse).

I've changed this to scroll more smoothly.

Also, if the vertical scrollbar isn't visible and a user's trying to scroll, it'll scroll horizontally.

### CODE REVIEW

**Comment by irgolic** [comment]
If someone could give this a whirl with their own mouse, I'd be grateful!

**Comment by lanzagar** [comment]
> Currently, if you hold shift and scroll, each turn of the scroll wheel will scroll a full horizontal distance (at least with my mouse).

Currently for me, shift does nothing (still scrolls vertically). But when putting the pointer over the horizontal scrollbar then the wheel does scroll horizontally. It is not full distance, but it is in larger jumps as when using the trackpad two-finger scrolling.

> I've changed this to scroll more smoothly.

After the change shift does work for me and behaves the same as putting the mouse pointer over the horizontal scrollbar. It is not any smoother than before or the same as with trackpad, but as mentioned I didn't experience "full distance" jumps anyway and can live with the minor jumps. But trackpad is definitely nicer and smoother for me.

> Also, if the vertical scrollbar isn't visible and a user's trying to scroll, it'll scroll horizontally.

Works for me after the PR and is I guess useful / more practical.

**Comment by thocevar** [comment]
I have the same experience on Windows as reported by Lan. However, currently Alt works for horizontal scrolling and not Shift. Afterwards, both Alt and Shift can be used to scroll horizontally.

**Comment by markotoplak** [comment]
Works nicely on a Mac.

**Comment by lanzagar** [comment]
As @thocevar found out, Alt worked before (for me as well).
If we want to change that to Shift I don't really have a preference since I don't use this frequently and aren't used to anything from other programs either. But we should probably choose one option and stick to it?

**Comment by janezd** [comment]
Alt looks more reasonable, because it Alt-ers the behaviour. Shift sounds select-ish.

**Comment by irgolic** [comment]
Shift+Scroll is a Mac shortcut for horizontal scrolling.
I could make it Alt on Windows/Linux, Shift on Mac? Or either Alt or Shift on both?

**Comment by irgolic** [comment]
I've pushed a change that uses Shift on Mac and Alt on Win/Linux.

Supposed new state of PR:
- [ ] Windows scrolls horizontally with Alt
- [ ] Linux scrolls horizontally with Alt
- [ ] Mac scrolls horizontally with Shift

**Comment by ajdapretnar** [comment]
I use shift *a lot* for horizontal scrolling. It is a default on Mac and I wouldn't change it for this OS. For Win & Linux: up to you guys.

**Pull request merged**
